// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-disable-preview'
  | 'pref-footer'
  | 'pref-popup-height'
  | 'pref-popup-width'
  | 'pref-title';
