// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "disablePreview": boolean;
      "lockPopupSize": boolean;
      "popupWidth": number;
      "popupHeight": number;
    };
  }
}
